### ISSUE TITLE
Broken CSS for team memberes on projects page

### ISSUE THREAD

**Issue by xbili** [cs3216/cs3216.github.io#4]
Something broke here :(

![screen shot 2016-08-15 at 15 36 58](https://cloud.githubusercontent.com/assets/4846457/17682069/2d3d1b7c-62fe-11e6-8819-c0d9ad2ffd56.png)

**Comment by mauris** [comment]
The `:after` rule with the `content: ", "` does not increase the width of the `<li>` and hence it wraps and break new line.

**Comment by mauris** [comment]
fixed in 28aeb26f9ce478a466c02c0367861dc2d5f16dfa
